version: '2'
services:
    producer:
        container_name: message-producer
        build: ./producer
        links:
        - rabbit:rabbit
        ports:
        - 5000:80
        environment: 
        - RABBITMQ_URI=rabbit
        - RABBITMQ_EXCHANGE=test
        - RABBITMQ_ROUTINGKEY=test.tb
    consumer:
        container_name: message-consumer
        build: ./consumer
        depends_on:
        - rabbit
        links:
        - rabbit:rabbit
        environment: 
        - RABBITMQ_URI=rabbit
    rabbit:
        container_name: rabbit-test
        hostname: rabbit-node-1
        image: rabbitmq:management-alpine
        ports:
        - 15672:15672