version: '2'
services:
    producer:
        container_name: message-producer
        build: ./producer
        links:
        - rabbit:rabbit
        ports:
        - 5000:80
        environment: 
        - RABBITMQ_URI=rabbit
    consumer:
        container_name: message-consumer
        build: ./consumer
        depends_on:
        - rabbit
        links:
        - rabbit:rabbit
        ports:
        - 5001:80
        environment: 
        - RABBITMQ_URI=rabbit
    portal:
        container_name: rabbit-portal
        build: ./portal
        depends-on:
        - rabbit
        - consumer
        - producer
        links:
        - consumer:consumer
        - producer:producer
        ports:
        - 8080:4200
    rabbit:
        container_name: rabbit-test
        hostname: rabbit-node-1
        image: rabbitmq:management-alpine
        ports:
        - 15672:15672