FROM microsoft/aspnetcore-build
WORKDIR /app

RUN npm install -g @angular/cli
RUN npm install -g typescript
RUN npm install -g typings

ENV RABBITMQ_USERNAME=guest
ENV RABBITMQ_PASSWORD=guest

COPY . .

RUN npm install
RUN npm build

RUN dotnet restore
RUN dotnet publish -c Release -o out

ENTRYPOINT ["dotnet", "out/consumer.dll"]